from __future__ import annotations

import re
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_symbols(header_path: Path) -> list[str]:
    symbols: list[str] = []
    seen: set[str] = set()

    for raw_line in header_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line.endswith(");"):
            continue
        if "typedef" in line or "(*" in line:
            continue

        match = re.search(r"\b(gl[A-Za-z0-9_]+)\s*\(", line)
        if not match:
            continue

        symbol = match.group(1)
        if symbol in seen:
            continue
        seen.add(symbol)
        symbols.append(symbol)

    return symbols


def render(symbols: list[str]) -> str:
    lines = [
        "// Generated by tools/generate_gx2gl_proc_table.py",
        "",
        "static const GX2GLProcEntry kGX2GLCoreProcTable[] = {",
    ]

    for symbol in symbols:
        lines.append(f'    {{"{symbol}", reinterpret_cast<GX2GL_Proc>({symbol})}},')

    lines.extend(
        [
            "};",
            "",
            "static const size_t kGX2GLCoreProcCount =",
            "    sizeof(kGX2GLCoreProcTable) / sizeof(kGX2GLCoreProcTable[0]);",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    root = repo_root()
    header = root / "include" / "gl" / "gl.h"
    out_path = root / "src" / "core" / "gx2gl_proc_table.inc"
    symbols = parse_symbols(header)
    out_path.write_text(render(symbols), encoding="utf-8")
    print(f"Wrote {len(symbols)} core proc mappings to {out_path}")


if __name__ == "__main__":
    main()
